version: 2
jobs:
  build:
    docker:
    - image: cibuilds/github:latest
    steps:
    - checkout
    - run: |
        rm -rf .circleci .git
        wget https://github.com/convertigo/prepare-pre-built-database/releases/download/1.3/prepare-pre-built-database-1.3.jar
        cd ..
        mv project lib_PrepareFSDatabase 
        mkdir artifacts
        zip -r artifacts/lib_PrepareFSDatabase.car lib_PrepareFSDatabase
    - store_artifacts:
        path: /root/artifacts
    - persist_to_workspace:
        root: .
        paths:
        - artifacts
  release:
    docker:
    - image: cibuilds/github:latest
    steps:
    - attach_workspace:
        at: .
    - run: |
        VERSION="1.3.0"
        ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} artifacts
workflows:
  version: 2
  all:
    jobs:
    - build:
        filters:
          tags:
            only: /^\d+\..*$/
    - release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\..*$/