version: 2
jobs:
  build:
    docker:
    - image: cibuilds/github:latest
    steps:
    - checkout
    - run: |
        ls -lha
        pwd
        wget https://github.com/convertigo/prepare-pre-built-database/releases/download/1.3/prepare-pre-built-database-1.3.jar
        ls -lha
    - persist_to_workspace:
        root: build
        paths:
        - libs
  release:
    docker:
    - image: cibuilds/github:latest
    steps:
    - attach_workspace:
        at: .
    - run: |
        VERSION=$(ls libs/*.jar | sed -n -e "s/.*-\(.*\)\.jar/\1/p")
        echo "VERSION=$VERSION"
        ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./libs/
workflows:
  version: 2
  all:
    jobs:
    - build:
        filters:
          tags:
            only: /^\d+\..*$/
    - release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\..*$/