name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: cibuilds/github:latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Project for Deployment
        run: |
          rm -rf .github .git
          wget https://github.com/convertigo/prepare-pre-built-database/releases/download/1.5/prepare-pre-built-database-1.5.jar
          cd ..
          mv c8oprj-lib-prepare-fs-database lib_PrepareFSDatabase 
          mkdir c8oprj-lib-prepare-fs-database
          zip -r c8oprj-lib-prepare-fs-database/lib_PrepareFSDatabase.car lib_PrepareFSDatabase

      - name: Upload CAR File
        uses: actions/upload-artifact@v4
        with:
          name: lib_PrepareFSDatabase
          path: .

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    container: cibuilds/github:latest
    steps:
      - name: Download CAR File
        uses: actions/download-artifact@v4
        with:
          name: lib_PrepareFSDatabase

      - name: Deploy to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.car'
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
